# Give your project a personalized name!
name: not-dspace

services:
  web:
    # The "web" service must be exposed to the host
    ports:
      - 8080:80

  angular:
    # Overrides for DSpace UI must start with "DSPACE_", replacing dots with
    # underscores, and arrays are addressed by giving an index number. The
    # HEADTAGS are here for reference, but they aren't actually being respected
    # for some reason.
    environment:
      DSPACE_THEMES_0_NAME: custom
      DSPACE_THEMES_0_HEADTAGS_0_TAGNAME: link
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_REL: icon
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_HREF: /path/to/favicon-32x32.png
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_SIZES: any
    # Uncomment to expose 4000 directly, e.g., to debug the frontend without
    # going through Apache httpd
    #ports:
    #  - 4000:4000

  rest:
    environment:
      # Example maven flags from the original DSpace docker setup for faster
      # build (but probably harder to debug? Comments didn't make it clear what
      # the downside is)
      MAVEN_FLAGS: -P-test-environment -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxml.skip=true

      # Give your site a fancy name!
      dspace__P__name: 'My First DSpace'

      # These are mandatory, and must match the *public* URL, not the internal
      # URL. If you use 8080 for the port in the "web" service above, these
      # settings will work as-is.
      dspace__P__server__P__url: http://localhost:8080/server
      dspace__P__ui__P__url: http://localhost:8080

    # Use a local dir for configs. Note that the environment overrides this!
    # (e.g., solr__P__server, db__P__url, etc.)
    volumes:
      - ./dspace-rest/config:/dspace/config
