# Give your project a personalized name!
name: not-dspace

# You must pick something here! This is configured in overrides to avoid
# potential collisions when standing up other compose stacks (or needing to run
# two SB stacks at once)
networks:
  dspacenet:
    ipam:
      config:
        - subnet: 172.23.78.0/24

# "web" must be exposed to the host!
services:
  web:
    # The ip addr must be in the configured subnet
    networks:
      dspacenet:
        ipv4_address: 172.23.78.240
    environment:
      # Set this to match the shibd service's static IP below
      SHIB_TCP_LISTENER_ADDRESS: 172.23.78.245
    ports:
      - 8080:80

  shibd:
    networks:
      dspacenet:
        ipv4_address: 172.23.78.245

  angular:
    # Overrides for DSpace UI must start with "DSPACE_", replacing dots with
    # underscores, and arrays are addressed by giving an index number. The
    # HEADTAGS are here for reference, but they aren't actually being respected
    # for some reason.
    environment:
      DSPACE_THEMES_0_NAME: custom
      DSPACE_THEMES_0_HEADTAGS_0_TAGNAME: link
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_REL: icon
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_HREF: /path/to/favicon-32x32.png
      DSPACE_THEMES_0_HEADTAGS_0_ATTRIBUTES_SIZES: any
    # Uncomment to expose 4000 directly, e.g., to debug the frontend without
    # going through Apache httpd
    #ports:
    #  - 4000:4000

  rest:
    environment:
      # Example maven flags from the original DSpace docker setup for faster
      # build (but probably harder to debug? Comments didn't make it clear what
      # the downside is)
      MAVEN_FLAGS: -P-test-environment -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxml.skip=true

      # Give your site a fancy name!
      dspace__P__name: 'My First DSpace'

      # These are mandatory, and must match the *public* URL, not the internal
      # URL. If you use 8080 for the port in the "web" service above, these
      # settings will work as-is.
      dspace__P__server__P__url: http://localhost:8080/server
      dspace__P__ui__P__url: http://localhost:8080

      # This needs to match the dspacenet range
      proxies__P__trusted__P__ipranges: "172.23.78.0/24"

      # Shib login URL. Note: you *must* provide the full URL, not just a path,
      # otherwise DSpace will decide for some reason that it should be https!
      authentication__D__shibboleth__P__lazysession__P__loginurl: "http://localhost:8080/Shibboleth.sso/Login"
