# env-replace builds the simple environment var replacer, which modifies
# shibboleth2.xml using environment vars
FROM golang:1 AS env-replace
WORKDIR /app
COPY ./env-replace.go /app/env-replace.go
RUN go build -o env-replace ./env-replace.go



# "base" installs the common elements we want for both shibd and apache. We do
# install apache here even though it's not needed for shibd, as it makes the
# two final images share more layers, saving a bit of space.
FROM rockylinux/rockylinux:9 AS base

COPY --from=env-replace /app/env-replace /usr/bin/env-replace
COPY ./conf/apache/shib-sp.repo /etc/yum.repos.d/shib-sp.repo
RUN dnf update -y && dnf upgrade -y
RUN dnf install -y shibboleth httpd

COPY ./conf/apache/log.conf /etc/httpd/conf.d/00-log.conf
COPY ./conf/apache/sb-proxy.base /etc/httpd/conf.d/10-sb-proxy.base
RUN rm /etc/httpd/conf.d/welcome.conf

COPY ./conf/apache/shibboleth2.base /etc/shibboleth/shibboleth2.base
COPY ./conf/apache/entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# shibd: standalone shibboleth listener
FROM base AS shibd
EXPOSE 1600
CMD ["shibd", "-F"]

# Apache httpd container - reverse proxy for the rest of the stack plus
# shibboleth handler
FROM base AS apache
STOPSIGNAL SIGWINCH
COPY conf/apache/httpd-foreground /usr/local/bin
EXPOSE 80
CMD ["httpd-foreground"]
