FROM docker.io/golang:1-alpine AS build

RUN apk update && apk upgrade
RUN apk add make git

WORKDIR /usr/local/src/turnstile-proxy
RUN git clone https://github.com/uoregon-libraries/turnstile-proxy-server.git -b v3.0.0 .
RUN make

WORKDIR /template-maker
ADD Makefile .
ADD tps-templates tps-templates
ADD tools tools
RUN make clean && make final-templates
RUN find /template-maker

FROM alpine AS app
WORKDIR /usr/local/tps
COPY --from=build /usr/local/src/turnstile-proxy/bin/tps tps
COPY --from=build /template-maker/tps-templates/challenge.go.html /var/local/tps/templates/challenge.go.html
COPY --from=build /template-maker/tps-templates/failed.go.html /var/local/tps/templates/failed.go.html

# Env values we don't need to let the user configure
ENV GIN_MODE=release
ENV BIND_ADDR=:8080
ENV PROXY_TARGET=http://web:18081
ENV LOG_DB_PATH=/var/local/tps/data/tps.db

ENTRYPOINT ["/usr/local/tps/tps"]
CMD ["serve"]
