# env-replace builds the simple environment var replacer, which modifies the
# httpd config using environment vars
FROM docker.io/golang:1 AS env-replace
WORKDIR /app
COPY ./env-replace.go /app/env-replace.go
RUN go build -o env-replace ./env-replace.go


FROM docker.io/rockylinux/rockylinux:9

COPY --from=env-replace /app/env-replace /usr/bin/env-replace
RUN dnf update -y && dnf upgrade -y
RUN dnf install -y httpd

COPY ./conf/apache/log.conf /etc/httpd/conf.d/00-log.conf
COPY ./conf/apache/sb-proxy.base /etc/httpd/conf.d/10-sb-proxy.base
RUN rm /etc/httpd/conf.d/welcome.conf

COPY ./conf/apache/entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

STOPSIGNAL SIGWINCH
COPY conf/apache/httpd-foreground /usr/local/bin
EXPOSE 80
CMD ["httpd-foreground"]
